import React from 'react';
import './App.css';

function App() {
  return (
    <div className="App">
      
      <div className="nav-bar">  
        <a href="./public/index.html" className="logo" />
        <div style={{display: "flex", marginRight:"3%"}}>  
          <div className="options">Como se<br />proteger ?</div>
          <div className="options">Grupo <br />de risco</div>
          <div className="options">Sintomas</div>
        </div>
      </div>

      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
      <p>AUIOEIUOAOEIUAOIUEOIUAeAUIOEIUOAOEIUAOIUEOIUAe <br /></p>
    </div>
  );
}

export default App;
